#!/usr/bin/env python3
"""Ingest AI-generated naming candidates into the SQLite candidate lake.

This tool imports candidate names from:
- --names (comma-separated)
- --input text file (one name per line)
- --input JSON file (array of strings or objects with {"name": "..."}).

It stores AI provenance metadata (model/provider/prompt) and leaves candidates
in `new` state for deterministic validation by the main pipeline.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sqlite3
from pathlib import Path

import naming_db as ndb


def now_iso() -> str:
    return dt.datetime.now().isoformat(timespec='seconds')


def load_input_candidates(path: Path) -> list[str]:
    if not path.exists():
        return []
    if path.suffix.lower() == '.json':
        data = json.loads(path.read_text(encoding='utf-8'))
        if isinstance(data, list):
            names: list[str] = []
            for item in data:
                if isinstance(item, str):
                    names.append(item.strip())
                elif isinstance(item, dict) and isinstance(item.get('name'), str):
                    names.append(item['name'].strip())
            return [name for name in names if name]
        return []

    names = []
    for line in path.read_text(encoding='utf-8').splitlines():
        name = line.strip()
        if name:
            names.append(name)
    return names


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Ingest AI-generated candidate names into naming DB.')
    parser.add_argument('--db', default='docs/branding/naming_pipeline.db', help='SQLite DB path.')
    parser.add_argument(
        '--names',
        default='',
        help='Comma-separated names generated by AI.',
    )
    parser.add_argument(
        '--input',
        default='',
        help='Optional input file (.txt or .json) with candidate names.',
    )
    parser.add_argument('--scope', choices=['dach', 'eu', 'global'], default='global')
    parser.add_argument('--gate', choices=['strict', 'balanced'], default='balanced')
    parser.add_argument('--model', default='', help='AI model identifier, e.g. google/gemini-3-pro-preview')
    parser.add_argument('--provider', default='', help='AI provider, e.g. openrouter/pal')
    parser.add_argument('--prompt', default='', help='Prompt snippet or prompt ID used for generation.')
    parser.add_argument('--source-label', default='ai_ingest', help='Source label for provenance.')
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    names = [name.strip() for name in args.names.split(',') if name.strip()]
    if args.input:
        names.extend(load_input_candidates(Path(args.input)))

    # Preserve order while deduplicating by normalized key.
    seen: set[str] = set()
    deduped: list[str] = []
    for name in names:
        key = ndb.normalize_name(name)
        if not key or key in seen:
            continue
        seen.add(key)
        deduped.append(name)

    if not deduped:
        print('No candidate names provided to ingest.')
        return 1

    db_path = Path(args.db)
    db_path.parent.mkdir(parents=True, exist_ok=True)

    with sqlite3.connect(db_path) as conn:
        ndb.ensure_schema(conn)
        run_id = ndb.create_run(
            conn,
            source_path=args.input or 'cli_names',
            scope=args.scope,
            gate_mode=args.gate,
            variation_profile='ai',
            status='completed',
            config={
                'source': 'ai_ingest',
                'model': args.model,
                'provider': args.provider,
                'prompt': args.prompt,
                'source_label': args.source_label,
                'candidate_count': len(deduped),
                'ingested_at': now_iso(),
            },
            summary={
                'ingested_count': len(deduped),
            },
        )

        inserted = 0
        for name in deduped:
            candidate_id = ndb.upsert_candidate(
                conn,
                name_display=name,
                total_score=None,
                risk_score=None,
                recommendation=None,
            )
            ndb.add_source(
                conn,
                candidate_id=candidate_id,
                run_id=run_id,
                source_type='ai',
                source_label=args.source_label,
                metadata={
                    'model': args.model,
                    'provider': args.provider,
                    'prompt': args.prompt,
                },
            )
            inserted += 1

        conn.commit()

    print(
        f'ai_ingest_complete run_id={run_id} candidates={inserted} db={db_path} '
        f'source_label={args.source_label}'
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())

